### ISSUE TITLE
Missing ADCRead.h

### ISSUE THREAD

**Issue by Lizard-King101** [ahmsville/Magnetic_rotary_encoding#1]
Not sure what i'm missing but I was testing it out with both Arduino pro Micro and the Seeeduino XAIO. any help fixing this issue? I would really appreciate any info on the mysterious `ADCRead.h`

```
MagRotaryEncoding.h:13:10: fatal error: ADCRead.h: No such file or directory
 #include "ADCRead.h"
          ^~~~~~~~~~~
```
I tried looking for anything about ADCRead.h on google but hit a dead end. even tried using a library called ADC.h but that was Teensy only.

**Comment by Lizard-King101** [comment]
@ahmsville you there buddy?

**Comment by ahmsville** [comment]
Hi @Lizard-King101  apologies for the inconvenience, the ADCRead is on a separate repository,  but i have just updated the Magnetic rotary encoding repository to contain these file locally, so simply clone this repository again and you should be good to go.
If you have any other questions, please let me know.
